# Tutorial de Python

## Introducción

El siguiente tutorial fue tomado de "The Python Tutorial": https://docs.python.org/3/tutorial/index.html, como parte del Task 1: Get Started with Data Science and Python del módulo 5: Data Science with Python del curso Data Analytics & Big Data, en la Universidad Cenfotec.

Alumno: Michael Fallas León.

## 1. Abriendo tu apetito

Python es simple de usar, pero es un lenguaje de programación real, que ofrece mucha más estructura y soporte para programas grandes que los scripts de shell o los archivos por lotes pueden ofrecer. Por otro lado, Python también ofrece mucha más verificación de errores que C y, al ser un lenguaje de muy alto nivel, tiene incorporados tipos de datos de alto nivel, como arreglos flexibles y diccionarios. Debido a sus tipos de datos más generales, Python es aplicable a un dominio de problemas mucho más grande que Awk o incluso Perl, sin embargo, muchas cosas son al menos tan fáciles en Python como en esos idiomas.

Python le permite dividir su programa en módulos que pueden reutilizarse en otros programas de Python. Viene con una gran colección de módulos estándar que puede usar como base de sus programas, o como ejemplos para comenzar a aprender a programar en Python. Algunos de estos módulos proporcionan elementos como E/S de archivos, llamadas al sistema, sockets e incluso interfaces para kits de herramientas de interfaz gráfica de usuario como Tk.

Python es un lenguaje interpretado, que puede ahorrarle un tiempo considerable durante el desarrollo del programa porque no es necesario compilar ni vincular. El intérprete se puede usar de forma interactiva, lo que facilita experimentar con las características del lenguaje, escribir programas descartables o probar funciones durante el desarrollo de programas ascendentes. También es una práctica calculadora de escritorio.

Python permite que los programas se escriban de forma compacta y legible. Los programas escritos en Python suelen ser mucho más cortos que los programas C, C ++ o Java equivalentes, por varias razones:
   - los tipos de datos de alto nivel le permiten expresar operaciones complejas en una sola declaración;
   - la agrupación de instrucciones se realiza mediante sangría en lugar de corchetes iniciales y finales;
   - no son necesarias declaraciones de variables o argumentos.

Python es extensible: si sabe programar en C, es fácil agregar una nueva función o módulo incorporado al intérprete, ya sea para realizar operaciones críticas a la máxima velocidad o para vincular los programas de Python a bibliotecas que solo pueden estar disponibles en forma binaria (como una biblioteca de gráficos específica del proveedor). Una vez que esté realmente enganchado, puede vincular el intérprete de Python a una aplicación escrita en C y usarlo como una extensión o lenguaje de comando para esa aplicación.

En el próximo capítulo, se explican las mecánicas del uso del intérprete. Esta es información bastante mundana, pero esencial para probar los ejemplos que se muestran más adelante.

El resto del tutorial presenta varias características del lenguaje y el sistema Python a través de ejemplos, comenzando con expresiones simples, declaraciones y tipos de datos, a través de funciones y módulos, y finalmente tocando conceptos avanzados como excepciones y clases definidas por el usuario.

## 2. Usando Python como Intérprete

### 2.1. Invocando el intérprete

El intérprete de Python generalmente se instala como /usr/local/bin/python3.8 en aquellas máquinas donde está disponible; poner /usr/local/bin en la ruta de búsqueda del shell de Unix permite iniciarlo escribiendo el comando:

    python3.8

Al escribir un carácter de fin de archivo (Control-D en Unix, Ctrl-Z en Windows) en el indicador principal, el intérprete sale con un estado de salida cero. Si eso no funciona, puede salir del intérprete escribiendo el siguiente comando: quit ().

Una segunda forma de iniciar el intérprete es python -c command [arg] ..., que ejecuta la (s) instrucción (es) en el comando, de forma análoga a la opción -c del shell. Dado que las declaraciones de Python a menudo contienen espacios u otros caracteres que son especiales para el shell, generalmente se recomienda citar el comando en su totalidad con comillas simples.

Algunos módulos de Python también son útiles como scripts. Estos pueden invocarse usando el módulo python -m [arg] ..., que ejecuta el archivo fuente del módulo como si hubiera deletreado su nombre completo en la línea de comando.

Cuando se usa un archivo de secuencia de comandos, a veces es útil poder ejecutar la secuencia de comandos e ingresar al modo interactivo después. Esto se puede hacer pasando -i antes del script.

Todas las opciones de línea de comando se describen en Línea de comando y entorno (https://docs.python.org/3/using/cmdline.html#using-on-general).

#### 2.1.1. Paso de argumento
Cuando el intérprete lo conoce, el nombre del script y los argumentos adicionales se convierten en una lista de cadenas y se asignan a la variable argv en el módulo sys. Puede acceder a esta lista ejecutando import sys. La longitud de la lista es al menos uno; cuando no se dan guiones ni argumentos, sys.argv [0] es una cadena vacía. Cuando el nombre del script se da como '-' (que significa entrada estándar), sys.argv [0] se establece en '-'. Cuando se usa el comando -c, sys.argv [0] se establece en '-c'. Cuando se utiliza el módulo -m, sys.argv [0] se establece con el nombre completo del módulo ubicado. El procesamiento de opciones del intérprete de Python no consume las opciones que se encuentran después del comando -c o el módulo -m, sino que se dejan en sys.argv para que las controle el comando o el módulo.

#### 2.1.2. Modo interactivo
Cuando los comandos se leen desde un tty, se dice que el intérprete está en modo interactivo. En este modo, solicita el siguiente comando con la solicitud principal, generalmente tres signos mayores que (>>>); para líneas de continuación, se solicita con la solicitud secundaria, por defecto tres puntos (...). El intérprete imprime un mensaje de bienvenida indicando su número de versión y un aviso de copyright antes de imprimir el primer mensaje.

Para más información sobre el modo interactivo, vea Modo interactivo (https://docs.python.org/3/tutorial/appendix.html#tut-interac).

### 2.2. El intérprete y su ambiente

#### 2.2.1. Codificación de código fuente
Por defecto, los archivos fuente de Python se tratan como codificados en UTF-8. En esa codificación, los caracteres de la mayoría de los idiomas del mundo pueden usarse simultáneamente en literales de cadena, identificadores y comentarios, aunque la biblioteca estándar solo usa caracteres ASCII para los identificadores, una convención que cualquier código portátil debe seguir. Para mostrar todos estos caracteres correctamente, su editor debe reconocer que el archivo es UTF-8 y debe usar una fuente que admita todos los caracteres del archivo.

Para declarar una codificación distinta de la predeterminada, se debe agregar una línea de comentario especial como primera línea del archivo. La sintaxis es la siguiente:

    # -*- coding: encoding -*-

donde la codificación es uno de los códecs válidos admitidos por Python.

Por ejemplo, para declarar que se va a utilizar la codificación Windows-1252, la primera línea de su archivo de código fuente debe ser:

    # -*- coding: cp1252 -*-
    
Una excepción a la regla de la primera línea es cuando el código fuente comienza con una línea "shebang" de UNIX (https://docs.python.org/3/tutorial/appendix.html#tut-scripts). En este caso, la declaración de codificación debe agregarse como la segunda línea del archivo. Por ejemplo:

    #!/usr/bin/env python3
    # -*- coding: cp1252 -*-

## 3. Una Introducción Informal a Python


En los siguientes ejemplos, la entrada y la salida se distinguen por la presencia o ausencia de avisos (>>> y ...): para repetir el ejemplo, debe escribir todo después del aviso, cuando aparece el aviso; Las líneas que no comienzan con una solicitud se emiten desde el intérprete. Tenga en cuenta que una solicitud secundaria en una línea sola en un ejemplo significa que debe escribir una línea en blanco; Esto se utiliza para finalizar un comando de varias líneas.

Muchos de los ejemplos en este manual, incluso los ingresados ​​en la solicitud interactiva, incluyen comentarios. Los comentarios en Python comienzan con el carácter hash, #, y se extienden hasta el final de la línea física. Puede aparecer un comentario al comienzo de una línea o después de un espacio en blanco o código, pero no dentro de un literal de cadena. Un carácter hash dentro de un literal de cadena es solo un carácter hash. Como los comentarios son para aclarar el código y Python no los interpreta, pueden omitirse al escribir ejemplos.

Algunos ejemplos:

In [2]:
# this is the first comment
spam = 1  # and this is the second comment
          # ... and now a third!
text = "# This is not a comment because it's inside quotes."

### 3.1. Usando Python como calculador

Probemos algunos comandos simples de Python. Inicie el intérprete y espere la solicitud principal, >>>.

#### 3.1.1. Números
El intérprete actúa como una simple calculadora: puede escribirle una expresión y escribirá el valor. La sintaxis de expresión es sencilla: los operadores +, -, * y / funcionan igual que en la mayoría de los otros lenguajes (por ejemplo, Pascal o C); los paréntesis (()) se pueden usar para agrupar. Por ejemplo:

In [4]:
2 + 2

1.6

In [6]:
50 - 5*6

20

In [5]:
(50 - 5*6) / 4

5.0

In [7]:
8 / 5  # division always returns a floating point number

1.6

Los números enteros (por ejemplo, 2, 4, 20) tienen tipo int, los que tienen una parte fraccional (por ejemplo, 5.0, 1.6) tienen tipo flotante. Veremos más sobre los tipos numéricos más adelante en el tutorial.

La división (/) siempre devuelve un flotador. Para hacer la división y obtener un resultado entero (descartando cualquier resultado fraccionario) puede usar el operador //; para calcular el resto puedes usar%:

In [8]:
17 / 3  # classic division returns a float

5.666666666666667

In [9]:
17 // 3  # floor division discards the fractional part

5

In [12]:
17 % 3  # the % operator returns the remainder of the division

2

In [13]:
5 * 3 + 2  # result * divisor + remainder

17

Con Python, es posible usar el operador ** para calcular potencias:

In [14]:
5 ** 2  # 5 squared

25

In [15]:
2 ** 7  # 2 to the power of 7

128

El signo igual (=) se usa para asignar un valor a una variable. Posteriormente, no se muestra ningún resultado antes del siguiente mensaje interactivo:

In [16]:
width = 20

In [17]:
height = 5 * 9

In [18]:
width * height

900

Si una variable no está "definida" (se le asigna un valor), intentar usarla le dará un error:

In [19]:
n  # try to access an undefined variable

NameError: name 'n' is not defined

Hay soporte completo para coma flotante; Los operadores con operandos de tipo mixto convierten el operando entero en coma flotante:

In [20]:
4 * 3.75 - 1

14.0

En modo interactivo, la última expresión impresa se asigna a la variable _. Esto significa que cuando usa Python como una calculadora de escritorio, es algo más fácil continuar con los cálculos, por ejemplo:

In [21]:
tax = 12.5 / 100

In [22]:
price = 100.50

In [23]:
price * tax

12.5625

In [24]:
price + _

113.0625

In [25]:
round(_, 2)

113.06

Esta variable debe ser tratada como de solo lectura por el usuario. No le asigne un valor explícitamente: crearía una variable local independiente con el mismo nombre enmascarando la variable incorporada con su comportamiento mágico.

Además de int y float, Python admite otros tipos de números, como Decimal y Fraction. Python también tiene soporte incorporado para números complejos, y usa el sufijo j o J para indicar la parte imaginaria (por ejemplo, 3 + 5j).

#### 3.1.2. Strings
Además de los números, Python también puede manipular strings, que se pueden expresar de varias maneras. Se pueden incluir entre comillas simples ('...') o comillas dobles ("...") con el mismo resultado. \ se puede usar para escapar de las comillas:

In [26]:
'spam eggs'  # single quotes

'spam eggs'

In [27]:
'doesn\'t'  # use \' to escape the single quote...

"doesn't"

In [28]:
"doesn't"  # ...or use double quotes instead

"doesn't"

In [29]:
'"Yes," they said.'

'"Yes," they said.'

In [30]:
"\"Yes,\" they said."

'"Yes," they said.'

In [31]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

En el intérprete interactivo, el string de salida se incluye entre comillas y los caracteres especiales se escapan con barras invertidas. Si bien esto a veces puede verse diferente de la entrada (las comillas que encierran podrían cambiar), ambos strings son equivalentes. El string se encierra entre comillas dobles si el string contiene una comilla simple y no comillas dobles, de lo contrario se encierra entre comillas simples. La función print () produce una salida más legible, omitiendo las comillas adjuntas e imprimiendo caracteres escapados y especiales:

In [32]:
'"Isn\'t," they said.'

'"Isn\'t," they said.'

In [33]:
print('"Isn\'t," they said.')

"Isn't," they said.


In [34]:
s = 'First line.\nSecond line.'  # \n means newline

In [35]:
s  # without print(), \n is included in the output

'First line.\nSecond line.'

In [36]:
print(s)  # with print(), \n produces a new line

First line.
Second line.


Si no desea que los caracteres precedidos por \ se interpreten como caracteres especiales, puede usar strings sin procesar agregando una r antes de la primera cita:

In [37]:
print('C:\some\name')  # here \n means newline!

C:\some
ame


In [38]:
print(r'C:\some\name')  # note the r before the quote

C:\some\name


Los strings literales pueden abarcar varias líneas. Una forma es usar comillas triples: "" "..." "" o '' '...' ''. El final de las líneas se incluye automáticamente en el string, pero es posible evitarlo agregando un \ al final de la línea. El siguiente ejemplo se 
produce el siguiente resultado (tenga en cuenta que la nueva línea inicial no está incluida):

In [39]:
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")

Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to



Los strings se pueden concatenar (pegar) con el operador + y repetir con *:

In [40]:
# 3 times 'un', followed by 'ium'
3 * 'un' + 'ium'

'unununium'

Dos o más strings literales (es decir, los encerrados entre comillas) uno al lado del otro se concatenan automáticamente.

In [41]:
'Py' 'thon'

'Python'

Esta característica es particularmente útil cuando desea romper strings largos:

In [42]:
text = ('Put several strings within parentheses '
        'to have them joined together.')
text

'Put several strings within parentheses to have them joined together.'

Sin embargo, esto solo funciona con dos literales, no con variables o expresiones:

In [43]:
prefix = 'Py'

In [44]:
prefix 'thon'  # can't concatenate a variable and a string literal

SyntaxError: invalid syntax (<ipython-input-44-c5901e312aa3>, line 1)

In [45]:
('un' * 3) 'ium'

SyntaxError: invalid syntax (<ipython-input-45-f4764cbe42a8>, line 1)

Si desea concatenar variables o una variable y un literal, use +:

In [46]:
prefix + 'thon'

'Python'

Los scrings pueden indexarse (subscripted), con el primer carácter con índice 0. No hay ningún tipo de carácter separado; un personaje es simplemente una cadena de tamaño uno:

In [47]:
word = 'Python'

In [48]:
word[0]  # character in position 0

'P'

In [49]:
word[5]  # character in position 5

'n'

Los índices también pueden ser números negativos, para comenzar a contar desde la derecha:

In [50]:
word[-1]  # last character

'n'

In [51]:
word[-2]  # second-last character

'o'

In [52]:
word[-6]

'P'

Tenga en cuenta que dado que -0 es igual a 0, los índices negativos comienzan desde -1.

Además de la indexación, también se admite la división. Si bien la indexación se usa para obtener caracteres individuales, la división le permite obtener un substring:

In [53]:
word[0:2]  # characters from position 0 (included) to 2 (excluded)

'Py'

In [54]:
word[2:5]  # characters from position 2 (included) to 5 (excluded)

'tho'

Observe cómo siempre se incluye el inicio y siempre se excluye el final. Esto asegura que s [: i] + s [i:] sea siempre igual a s:

In [55]:
word[:2] + word[2:]

'Python'

In [56]:
word[:4] + word[4:]

'Python'

Los índices de corte tienen valores predeterminados útiles; un primer índice omitido por defecto es cero, un segundo índice omitido por defecto al tamaño de la cadena que se corta.

In [57]:
word[:2]   # character from the beginning to position 2 (excluded)

'Py'

In [58]:
word[4:]   # characters from position 4 (included) to the end

'on'

In [59]:
word[-2:]  # characters from the second-last (included) to the end

'on'

Una forma de recordar cómo funcionan los cortes es pensar en los índices como apuntando entre caracteres, con el borde izquierdo del primer carácter numerado 0. Luego, el borde derecho del último carácter de una cadena de n caracteres tiene un índice n, por ejemplo:

     +---+---+---+---+---+---+
     | P | y | t | h | o | n |
     +---+---+---+---+---+---+
     0   1   2   3   4   5   6
    -6  -5  -4  -3  -2  -1

La primera fila de números da la posición de los índices 0 ... 6 en la cadena; la segunda fila da los índices negativos correspondientes. El corte de i a j consta de todos los caracteres entre los bordes etiquetados como i y j, respectivamente.

Para índices no negativos, la longitud de un segmento es la diferencia de los índices, si ambos están dentro de los límites. Por ejemplo, la longitud de la palabra [1:3] es 2.

Intentar usar un índice que sea demasiado grande dará como resultado un error:

In [60]:
word[42]  # the word only has 6 characters

IndexError: string index out of range

Sin embargo, los índices de corte fuera de rango se manejan con gracia cuando se usan para cortar:

In [61]:
word[4:42]

'on'

In [62]:
word[42:]

''

Los strings de Python no se pueden cambiar, son inmutables. Por lo tanto, la asignación a una posición indexada en la cadena da como resultado un error:

In [63]:
word[0] = 'J'

TypeError: 'str' object does not support item assignment

In [64]:
word[2:] = 'py'

TypeError: 'str' object does not support item assignment

Si necesita una cadena diferente, debe crear una nueva:

In [65]:
'J' + word[1:]

'Jython'

In [66]:
word[:2] + 'py'

'Pypy'

La función incorporada len () devuelve la longitud de una cadena:

In [67]:
s = 'supercalifragilisticexpialidocious'

In [68]:
len(s)

34

#### 3.1.3. Listas
Python conoce varios tipos de datos compuestos, utilizados para agrupar otros valores. La más versátil es la lista, que se puede escribir como una lista de valores (elementos) separados por comas entre corchetes. Las listas pueden contener elementos de diferentes tipos, pero generalmente todos los elementos tienen el mismo tipo.

In [69]:
squares = [1, 4, 9, 16, 25]

In [70]:
squares

[1, 4, 9, 16, 25]

Al igual que los strings (y todos los demás tipos de secuencia incorporados), las listas pueden indexarse ​​y dividirse:

In [71]:
squares[0]  # indexing returns the item

1

In [72]:
squares[-1]

25

In [73]:
squares[-3:]  # slicing returns a new list

[9, 16, 25]

Todas las operaciones de división devuelven una nueva lista que contiene los elementos solicitados. Esto significa que el siguiente segmento devuelve un shallow copy (https://docs.python.org/3/library/copy.html#shallow-vs-deep-copy) de la lista:

In [74]:
squares[:]

[1, 4, 9, 16, 25]

Las listas también admiten operaciones como la concatenación:

In [75]:
squares + [36, 49, 64, 81, 100]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

A diferencia de los strings, que son inmutables, las listas son de tipo mutable, es decir, es posible cambiar su contenido:

In [76]:
cubes = [1, 8, 27, 65, 125]  # something's wrong here

In [77]:
4 ** 3  # the cube of 4 is 64, not 65!

64

In [78]:
cubes[3] = 64  # replace the wrong value

In [79]:
cubes

[1, 8, 27, 64, 125]

También puede agregar nuevos elementos al final de la lista, utilizando el método append() (veremos más acerca de los métodos más adelante):

In [80]:
cubes.append(216)  # add the cube of 6

In [81]:
cubes.append(7 ** 3)  # and the cube of 7

In [82]:
cubes

[1, 8, 27, 64, 125, 216, 343]

La asignación a sectores también es posible, y esto incluso puede cambiar el tamaño de la lista o borrarla por completo:

In [83]:
letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [84]:
letters

['a', 'b', 'c', 'd', 'e', 'f', 'g']

In [85]:
# replace some values
letters[2:5] = ['C', 'D', 'E']

In [86]:
letters

['a', 'b', 'C', 'D', 'E', 'f', 'g']

In [87]:
# now remove them
letters[2:5] = []

In [88]:
letters

['a', 'b', 'f', 'g']

In [89]:
# clear the list by replacing all the elements with an empty list
letters[:] = []

In [90]:
letters

[]

La función incorporada len() también se aplica a las listas:

In [91]:
letters = ['a', 'b', 'c', 'd']

In [92]:
len(letters)

4

Es posible anidar listas (crear listas que contengan otras listas), por ejemplo:

In [93]:
a = ['a', 'b', 'c']

In [94]:
n = [1, 2, 3]

In [95]:
x = [a, n]

In [96]:
x

[['a', 'b', 'c'], [1, 2, 3]]

In [97]:
x[0]

['a', 'b', 'c']

In [98]:
x[0][1]

'b'

### 3.2. Primeros pasos hacia la programación

Por supuesto, podemos usar Python para tareas más complicadas que sumar dos y dos juntas. Por ejemplo, podemos escribir una subsecuencia inicial de la serie de Fibonacci de la siguiente manera:

In [99]:
# Fibonacci series:
# the sum of two elements defines the next
a, b = 0, 1

In [101]:
while a < 10:
    print(a)
    a, b = b, a+b

0
1
1
2
3
5
8


Este ejemplo presenta varias características nuevas.

   - La primera línea contiene una asignación múltiple: las variables a y b obtienen simultáneamente los nuevos valores 0 y 1. En la última línea, esto se usa nuevamente, lo que demuestra que las expresiones en el lado derecho se evalúan primero antes de que cualquiera de las asignaciones tengan lugar. Las expresiones del lado derecho se evalúan de izquierda a derecha.
   - El bucle while se ejecuta mientras la condición (aquí: a <10) permanezca verdadera. En Python, como en C, cualquier valor entero distinto de cero es verdadero; cero es falso La condición también puede ser una cadena o un valor de lista, de hecho cualquier secuencia; cualquier cosa con una longitud distinta de cero es verdadera, las secuencias vacías son falsas. La prueba utilizada en el ejemplo es una comparación simple. Los operadores de comparación estándar se escriben igual que en C: <(menor que),> (mayor que), == (igual a), <= (menor o igual que),> = (mayor o igual que) y! = (no es igual a).
   - El cuerpo del bucle: la sangría es la forma en que Python agrupa las declaraciones. En el mensaje interactivo, debe escribir una pestaña o espacios para cada línea de sangría. En la práctica, preparará entradas más complicadas para Python con un editor de texto; Todos los editores de texto decentes tienen una función de sangría automática. Cuando una declaración compuesta se ingresa de manera interactiva, debe ir seguida de una línea en blanco para indicar la finalización (ya que el analizador no puede adivinar cuándo ha escrito la última línea). Tenga en cuenta que cada línea dentro de un bloque básico debe utilizar la misma cantidad de sangrías.
   - La función print () escribe el valor de los argumentos que se le dan. Se diferencia de solo escribir la expresión que desea escribir (como lo hicimos anteriormente en los ejemplos de la calculadora) en la forma en que maneja múltiples argumentos, cantidades en coma flotante y cadenas. Las cadenas se imprimen sin comillas, y se inserta un espacio entre los elementos, para que pueda formatear bien las cosas, de esta manera:

In [102]:
i = 256*256

In [103]:
print('The value of i is', i)

The value of i is 65536


El argumento final de la palabra clave se puede utilizar para evitar la nueva línea después de la salida, o finalizar la salida con una cadena diferente:

In [104]:
a, b = 0, 1

In [105]:
while a < 1000:
    print(a, end=',')
    a, b = b, a+b

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

## 4. Más Herramientas de Control de Flujo

Además de la declaración while que se acaba de presentar, Python usa las declaraciones habituales de control de flujo conocidas de otros lenguajes, con algunos giros.

### 4.1. Declaraciones con if


Quizás el tipo de declaración más conocido es la declaración if. Por ejemplo:

In [111]:
x = int(input("Please enter an integer: "))

Please enter an integer: 42


In [114]:
if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

More


Puede haber cero o más partes elif, y la parte else es opcional. La palabra clave "elif" es la abreviatura de "else if" y es útil para evitar una sangría excesiva. Una secuencia if ... elif ... elif ... es un sustituto de las declaraciones de cambio o de caso que se encuentran en otros idiomas.

### 4.2. Declaraciones for

La declaración for en Python difiere un poco de lo que puede estar acostumbrado en C o Pascal. En lugar de iterar siempre sobre una progresión aritmética de números (como en Pascal), o dar al usuario la capacidad de definir tanto el paso de iteración como la condición de detención (como C), la declaración for de Python itera sobre los elementos de cualquier secuencia (una lista o una cadena), en el orden en que aparecen en la secuencia. Por ejemplo (sin juego de palabras):

In [115]:
# Measure some strings:
words = ['cat', 'window', 'defenestrate']

In [116]:
for w in words:
    print(w, len(w))

cat 3
window 6
defenestrate 12


El código que modifica una colección mientras itera sobre esa misma colección puede ser difícil de entender. En cambio, generalmente es más sencillo recorrer una copia de la colección o crear una nueva colección:

    # Strategy:  Iterate over a copy
    for user, status in users.copy().items():
        if status == 'inactive':
            del users[user]

    # Strategy:  Create a new collection
    active_users = {}
    for user, status in users.items():
        if status == 'active':
            active_users[user] = status
            
### 4.3. La función range()


Si necesita iterar sobre una secuencia de números, la función incorporada range() es útil. Genera progresiones aritméticas:

In [118]:
for i in range(5):
    print(i)

0
1
2
3
4


El punto final dado nunca es parte de la secuencia generada; El rango (10) genera 10 valores, los índices legales para elementos de una secuencia de longitud 10. Es posible dejar que el rango comience en otro número, o especificar un incremento diferente (incluso negativo; a veces esto se llama el 'step'):

    range(5, 10)
       5, 6, 7, 8, 9

    range(0, 10, 3)
       0, 3, 6, 9
    
    range(-10, -100, -30)
      -10, -40, -70
      
Para iterar sobre los índices de una secuencia, puede combinar range() y len() de la siguiente manera:

In [120]:
a = ['Mary', 'had', 'a', 'little', 'lamb']

In [121]:
for i in range(len(a)):
    print(i, a[i])

0 Mary
1 had
2 a
3 little
4 lamb


En la mayoría de estos casos, sin embargo, es conveniente usar la función enumerate(), consulte Técnicas de bucle (https://docs.python.org/3/tutorial/datastructures.html#tut-loopidioms).

Algo extraño sucede si solo imprime un rango:

In [122]:
print(range(10))

range(0, 10)


En muchos sentidos, el objeto devuelto por range() se comporta como si fuera una lista, pero de hecho no lo es. Es un objeto que devuelve los elementos sucesivos de la secuencia deseada cuando se repite, pero en realidad no aparece en la lista, lo que ahorra espacio.

Decimos que dicho objeto es iterable, es decir, adecuado como objetivo para funciones y construcciones que esperan algo de lo que puedan obtener elementos sucesivos hasta que se agote el suministro. Hemos visto que la instrucción for es una construcción de este tipo, mientras que un ejemplo de una función que toma un iterable es sum():

In [123]:
sum(range(4))  # 0 + 1 + 2 + 3

6

Por último, quizás tenga curiosidad acerca de cómo obtener una lista de un rango. Aquí está la solución:

In [124]:
list(range(4))

[0, 1, 2, 3]

### 4.4. Declaraciones con break y continue, y oraciones con el bucle else


La declaración de break, como en C, se separa del encerramiento más interno para el ciclo while.

Las declaraciones de bucle pueden tener una cláusula else; se ejecuta cuando el ciclo termina por agotamiento del iterable (con for) o cuando la condición se vuelve falsa (con while), pero no cuando el ciclo se termina con una declaración de break. Esto se ejemplifica con el siguiente ciclo, que busca números primos:

In [128]:
for n in range(2, 10):
    for x in range(2, n):
        if n % x == 0:
            print(n, 'equals', x, '*', n//x)
            break
    else:
            # loop fell through without finding a factor
            print(n, 'is a prime number')

2 is a prime number
3 is a prime number
4 equals 2 * 2
5 is a prime number
6 equals 2 * 3
7 is a prime number
8 equals 2 * 4
9 equals 3 * 3


(Sí, este es el código correcto. Observe atentamente: la cláusula else pertenece al ciclo for, no a la instrucción if).

Cuando se usa con un bucle, la cláusula else tiene más en común con la cláusula else de una declaración try que con la de las declaraciones if: la cláusula else de una declaración try se ejecuta cuando no ocurre ninguna excepción, y la cláusula else de un ciclo se ejecuta cuando no hay interrupción ocurre. Para obtener más información sobre la declaración de prueba y las excepciones, consulte Manejo de excepciones (https://docs.python.org/3/tutorial/errors.html#tut-handling).

La instrucción continue, también tomada de C, continúa con la siguiente iteración del ciclo:

In [129]:
for num in range(2, 10):
    if num % 2 == 0:
        print("Found an even number", num)
        continue
    print("Found a number", num)

Found an even number 2
Found a number 3
Found an even number 4
Found a number 5
Found an even number 6
Found a number 7
Found an even number 8
Found a number 9


### 4.5. Declaraciones con pass

La declaración con pass no hace nada. Se puede usar cuando se requiere una declaración sintácticamente pero el programa no requiere ninguna acción. Por ejemplo:

Esto se usa comúnmente para crear clases mínimas:

Se puede usar otro pass de lugar como un marcador de posición para una función o cuerpo condicional cuando se trabaja en un nuevo código, lo que le permite seguir pensando en un nivel más abstracto. El pass se ignora en silencio:

### 4.6. Definiendo funciones


Podemos crear una función que escriba la serie de Fibonacci en un límite arbitrario:

In [1]:
def fib(n):    # write Fibonacci series up to n
    """Print a Fibonacci series up to n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
    print()

In [2]:
# Now call the function we just defined:
fib(2000)

0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 


La palabra clave def introduce una definición de función. Debe ir seguido del nombre de la función y la lista entre paréntesis de parámetros formales. Las declaraciones que forman el cuerpo de la función comienzan en la siguiente línea y deben usar sangría.

La primera declaración del cuerpo de la función puede ser opcionalmente un literal de cadena; este literal de cadena es el string de documentación de la función, docstring (https://docs.python.org/3/tutorial/controlflow.html#tut-docstrings). Existen herramientas que utilizan docstrings para producir automáticamente documentación en línea o impresa, o para permitir que el usuario navegue interactivamente a través del código; es una buena práctica incluir cadenas de documentos en el código que escriba, así que acostúmbrese a hacerlo.

La ejecución de una función introduce una nueva tabla de símbolos utilizada para las variables locales de la función. Más precisamente, todas las asignaciones de variables en una función almacenan el valor en la tabla de símbolos local; mientras que las referencias de variables se ven primero en la tabla de símbolos local, luego en las tablas de símbolos locales de las funciones de cierre, luego en la tabla de símbolos global y finalmente en la tabla de nombres incorporados. Por lo tanto, no se puede asignar directamente un valor dentro de una función a las variables globales y a las variables de las funciones de cierre (a menos que, para las variables globales, se nombren en una declaración global, o, para las variables de las funciones de cierre, se nombren en una declaración nonlocal), aunque pueden ser referenciado

Los parámetros reales (argumentos) de una llamada de función se introducen en la tabla de símbolos local de la función llamada cuando se llama; por lo tanto, los argumentos se pasan utilizando call by value (donde value siempre es una referencia de objeto, no el valor del objeto). Cuando una función llama a otra función, se crea una nueva tabla de símbolos local para esa llamada.

Una definición de función introduce el nombre de la función en la tabla de símbolos actual. El valor del nombre de la función tiene un tipo que el intérprete reconoce como una función definida por el usuario. Este valor puede asignarse a otro nombre que luego también puede usarse como una función. Esto sirve como un mecanismo general de cambio de nombre:

In [3]:
fib

<function __main__.fib(n)>

In [4]:
f = fib

In [5]:
f(100)

0 1 1 2 3 5 8 13 21 34 55 89 


Al provenir de otros idiomas, puede objetar que fib no es una función sino un procedimiento, ya que no devuelve un valor. De hecho, incluso las funciones sin una declaración return devuelven un valor, aunque sea bastante aburrido. Este valor se llama None (es un nombre incorporado). Escribir el valor None es normalmente suprimido por el intérprete si fuera el único valor escrito. Puede verlo si realmente desea usar print ():

In [6]:
fib(0)

In [7]:
print(fib(0))


None


Es simple escribir una función que devuelva una lista de los números de la serie de Fibonacci, en lugar de imprimirla:

In [8]:
def fib2(n):  # return Fibonacci series up to n
    """Return a list containing the Fibonacci series up to n."""
    result = []
    a, b = 0, 1
    while a < n:
        result.append(a)    # see below
        a, b = b, a+b
    return result

In [9]:
f100 = fib2(100)    # call it

In [10]:
f100                # write the result

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

Este ejemplo, como de costumbre, muestra algunas características nuevas de Python:

   - La declaración return regresa con un valor de una función. return sin un argumento de expresión devuelve None. Fallar al final de una función también devuelve None.
   - La declaración result.append (a) llama a un método del resultado del objeto de lista. Un método es una función que "pertenece" a un objeto y se llama obj.methodname, donde obj es algún objeto (esto puede ser una expresión), y methodname es el nombre de un método definido por el tipo de objeto. Diferentes tipos definen diferentes métodos. Los métodos de diferentes tipos pueden tener el mismo nombre sin causar ambigüedad. (Es posible definir sus propios tipos y métodos de objetos, usando clases, vea Clases) El método append () que se muestra en el ejemplo está definido para objetos de lista; agrega un nuevo elemento al final de la lista. En este ejemplo, es equivalente a resultado = resultado + [a], pero más eficiente.

### 4.7. Más funciones de definición

También es posible definir funciones con un número variable de argumentos. Hay tres formas, que se pueden combinar.

#### 4.7.1. Valores de argumento predeterminados
La forma más útil es especificar un valor predeterminado para uno o más argumentos. Esto crea una función que se puede invocar con menos argumentos de los que se define para permitir. Por ejemplo:

In [11]:
def ask_ok(prompt, retries=4, reminder='Please try again!'):
    while True:
        ok = input(prompt)
        if ok in ('y', 'ye', 'yes'):
            return True
        if ok in ('n', 'no', 'nop', 'nope'):
            return False
        retries = retries - 1
        if retries < 0:
            raise ValueError('invalid user response')
        print(reminder)

Esta función se puede llamar de varias maneras:

   - dando solo el argumento obligatorio: ask_ok ('¿Realmente quieres salir?')
   - dando uno de los argumentos opcionales: ask_ok ('¿OK para sobrescribir el archivo?', 2)
   - o incluso dando todos los argumentos: ask_ok ('¿OK para sobrescribir el archivo?', 2, '¡Vamos, solo sí o no!')

Este ejemplo también introduce la palabra clave in. Esto prueba si una secuencia contiene o no un cierto valor.

Los valores predeterminados se evalúan en el punto de definición de la función en el defining scope, de modo que

In [12]:
i = 5

In [13]:
def f(arg=i):
    print(arg)

In [14]:
i = 6

In [15]:
f()

5


Advertencia importante: el valor predeterminado se evalúa solo una vez. Esto hace la diferencia cuando el valor predeterminado es un objeto mutable como una lista, diccionario o instancias de la mayoría de las clases. Por ejemplo, la siguiente función acumula los argumentos que se le pasan en llamadas posteriores:

In [16]:
def f(a, L=[]):
    L.append(a)
    return L

In [17]:
print(f(1))

[1]


In [18]:
print(f(2))

[1, 2]


In [19]:
print(f(3))

[1, 2, 3]


Si no desea que el valor predeterminado se comparta entre llamadas posteriores, puede escribir la función de esta manera:

In [20]:
def f(a, L=None):
    if L is None:
        L = []
    L.append(a)
    return L

#### 4.7.2. Argumentos de palabras clave

Las funciones también se pueden invocar utilizando argumentos de palabras clave de la forma kwarg = valor. Por ejemplo, la siguiente función: si no desea que el valor predeterminado se comparta entre llamadas posteriores, puede escribir la función de esta manera:

In [21]:
def parrot(voltage, state='a stiff', action='voom', type='Norwegian Blue'):
    print("-- This parrot wouldn't", action, end=' ')
    print("if you put", voltage, "volts through it.")
    print("-- Lovely plumage, the", type)
    print("-- It's", state, "!")

acepta un argumento requerido (voltaje) y tres argumentos opcionales (estado, acción y tipo). Esta función se puede llamar de cualquiera de las siguientes maneras:

In [23]:
parrot(1000)                                          # 1 positional argument
parrot(voltage=1000)                                  # 1 keyword argument
parrot(voltage=1000000, action='VOOOOOM')             # 2 keyword arguments
parrot(action='VOOOOOM', voltage=1000000)             # 2 keyword arguments
parrot('a million', 'bereft of life', 'jump')         # 3 positional arguments
parrot('a thousand', state='pushing up the daisies')  # 1 positional, 1 keyword

-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't voom if you put 1000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't VOOOOOM if you put 1000000 volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's a stiff !
-- This parrot wouldn't jump if you put a million volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's bereft of life !
-- This parrot wouldn't voom if you put a thousand volts through it.
-- Lovely plumage, the Norwegian Blue
-- It's pushing up the daisies !


pero todas las siguientes llamadas serían inválidas:

In [24]:
parrot()                     # required argument missing
parrot(voltage=5.0, 'dead')  # non-keyword argument after a keyword argument
parrot(110, voltage=220)     # duplicate value for the same argument
parrot(actor='John Cleese')  # unknown keyword argument

SyntaxError: positional argument follows keyword argument (<ipython-input-24-2ac707ad11c1>, line 2)

En una llamada a función, los argumentos de palabras clave deben seguir argumentos posicionales. Todos los argumentos de palabras clave pasados deben coincidir con uno de los argumentos aceptados por la función (por ejemplo, actor no es un argumento válido para la función de parrot), y su orden no es importante. Esto también incluye argumentos no opcionales (por ejemplo, parrot(voltaje = 1000) también es válido). Ningún argumento puede recibir un valor más de una vez. Aquí hay un ejemplo que falla debido a esta restricción:

In [25]:
def function(a):
    pass

In [26]:
function(0, a=0)

TypeError: function() got multiple values for argument 'a'

Cuando está presente un parámetro de la forma ** name , recibe un diccionario que contiene todos los argumentos de palabras clave, excepto los correspondientes a un parámetro formal. Esto se puede combinar con un parámetro de la forma *name (descrito en la siguiente subsección) que recibe una tupla que contiene los argumentos posicionales más allá de la lista de parámetros formales. (*name debe aparecer antes de ** name). Por ejemplo, si definimos una función como esta:

In [27]:
def cheeseshop(kind, *arguments, **keywords):
    print("-- Do you have any", kind, "?")
    print("-- I'm sorry, we're all out of", kind)
    for arg in arguments:
        print(arg)
    print("-" * 40)
    for kw in keywords:
        print(kw, ":", keywords[kw])

Se podría llamar así:

In [28]:
cheeseshop("Limburger", "It's very runny, sir.",
           "It's really very, VERY runny, sir.",
           shopkeeper="Michael Palin",
           client="John Cleese",
           sketch="Cheese Shop Sketch")

-- Do you have any Limburger ?
-- I'm sorry, we're all out of Limburger
It's very runny, sir.
It's really very, VERY runny, sir.
----------------------------------------
shopkeeper : Michael Palin
client : John Cleese
sketch : Cheese Shop Sketch


Tenga en cuenta que se garantiza que el orden en que se imprimen los argumentos de las palabras clave coincide con el orden en que se proporcionaron en la llamada a la función.

#### 4.7.3. Parámetros especiales

Por defecto, los argumentos se pueden pasar a una función de Python por posición o explícitamente por palabra clave. Para facilitar la lectura y el rendimiento, tiene sentido restringir la forma en que se pueden pasar los argumentos para que un desarrollador solo tenga que mirar la definición de la función para determinar si los elementos se pasan por posición, por posición o palabra clave, o por palabra clave.

Una definición de función puede verse así:

    def f(pos1, pos2, /, pos_or_kwd, *, kwd1, kwd2):
          -----------    ----------     ----------
            |             |                  |
            |        Positional or keyword   |
            |                                - Keyword only
             -- Positional only
         
donde / y * son opcionales. Si se usan, estos símbolos indican el tipo de parámetro según cómo se pueden pasar los argumentos a la función: solo posicional, posicional o palabra clave y solo palabra clave. Los parámetros de palabras clave también se denominan parámetros con nombre.

##### 4.7.3.1. Argumentos Positional-or-Keyword
Si / y * no están presentes en la definición de la función, los argumentos se pueden pasar a una función por posición o por palabra clave.

##### 4.7.3.2. Parámetros Positional-Only
Mirando esto con un poco más de detalle, es posible marcar ciertos parámetros como solo posicionales. Si es solo posicional, el orden de los parámetros es importante y los parámetros no se pueden pasar por palabra clave. Los parámetros de solo posición se colocan antes de un / (barra inclinada). El / se usa para separar lógicamente los parámetros solo posicionales del resto de los parámetros. Si no hay / en la definición de la función, no hay parámetros solo posicionales.

Los parámetros que siguen a / pueden ser positional-or-keyword o keyword-only.

##### 4.7.3.3. Argumentos Keyword-Only
Para marcar los parámetros como solo palabras clave, indicando que los parámetros deben pasarse por argumento de palabra clave, coloque un * en la lista de argumentos justo antes del primer parámetro keywor-only.

##### 4.7.3.4. Ejemplos de funciones
Considere las siguientes definiciones de funciones de ejemplo prestando especial atención a los marcadores / y *:

**Nota:** algunos comandos requieren la versión de python 3.8, por lo que en ésta sección algunos ejercicios no se pueden ejecutar y, se obtiene errores en la sintáxis. Por lo tanto, se procede a escribir los resultados con céldas no ejecutables.

In [3]:
def standard_arg(arg):
    print(arg)

In [5]:
def kwd_only_arg(*, arg):
    print(arg)

La primera definición de función, standard_arg, la forma más familiar, no impone restricciones a la convención de llamada y los argumentos se pueden pasar por posición o palabra clave:

In [4]:
standard_arg(2)

2


In [6]:
standard_arg(arg=2)

2


La segunda función pos_only_arg está restringida a usar solo parámetros posicionales ya que hay un / en la definición de la función:

La tercera función kwd_only_args solo permite argumentos de palabras clave como se indica con un * en la definición de la función:

In [7]:
kwd_only_arg(3)

TypeError: kwd_only_arg() takes 0 positional arguments but 1 was given

In [8]:
kwd_only_arg(arg=3)

3


Y el último usa las tres convenciones de llamada en la misma definición de función:

Finalmente, considere esta definición de función que tiene una posible colisión entre el nombre del argumento posicional y ** kwds que tiene el nombre como clave:

In [9]:
def foo(name, **kwds):
    return 'name' in kwds

No hay una llamada posible que haga que devuelva True, ya que la palabra clave 'nombre' siempre se unirá al primer parámetro. Por ejemplo:

In [10]:
foo(1, **{'name': 2})

TypeError: foo() got multiple values for argument 'name'

Pero usando / (argumentos solo posicionales), es posible ya que permite el nombre como argumento posicional y 'nombre' como clave en los argumentos de palabras clave:

En otras palabras, los nombres de los parámetros solo posicionales se pueden usar en ** kwds sin ambigüedad.

##### 4.7.3.5. Recap
The use case will determine which parameters to use in the function definition:

Como orientación:

   - Use positional-only si desea que el nombre de los parámetros no esté disponible para el usuario. Esto es útil cuando los nombres de los parámetros no tienen un significado real, si desea imponer el orden de los argumentos cuando se llama a la función o si necesita tomar algunos parámetros posicionales y palabras clave arbitrarias.
   - Use keyword-only cuando los nombres tengan significado y la definición de la función sea más comprensible al ser explícito con los nombres o si desea evitar que los usuarios confíen en la posición del argumento que se pasa.
   - Para una API, use positional-only para evitar que se rompan los cambios de la API si el nombre del parámetro se modifica en el futuro.
   
#### 4.7.4. Listas de argumentos arbitario

Finalmente, la opción menos utilizada es especificar que se puede llamar a una función con un número arbitrario de argumentos. Estos argumentos estarán envueltos en una tupla (ver Tuplas y Secuencias). Antes del número variable de argumentos, pueden ocurrir cero o más argumentos normales.

In [13]:
def write_multiple_items(file, separator, *args):
    file.write(separator.join(args))

Normalmente, estos argumentos variados serán los últimos en la lista de parámetros formales, ya que recogen todos los argumentos de entrada restantes que se pasan a la función. Cualquier parámetro formal que ocurra después del parámetro * args son argumentos de "solo palabras clave", lo que significa que solo pueden usarse como palabras clave en lugar de argumentos posicionales.

In [14]:
def concat(*args, sep="/"):
    return sep.join(args)

In [15]:
concat("earth", "mars", "venus")

'earth/mars/venus'

In [16]:
concat("earth", "mars", "venus", sep=".")

'earth.mars.venus'

#### 4.7.5. Listas de unpacking argument

La situación inversa ocurre cuando los argumentos ya están en una lista o tupla pero necesitan ser desempaquetados para una llamada de función que requiere argumentos posicionales separados. Por ejemplo, la función incorporada range() espera iniciar y detener argumentos por separado. Si no están disponibles por separado, escriba la llamada a la función con el operador * para desempaquetar los argumentos de una lista o tupla:

In [17]:
list(range(3, 6))            # normal call with separate arguments

[3, 4, 5]

In [18]:
args = [3, 6]

In [19]:
list(range(*args))            # call with arguments unpacked from a list

[3, 4, 5]

#### 4.7.6. Expresiones lambda

Se pueden crear pequeñas funciones anónimas con la palabra clave lambda. Esta función devuelve la suma de sus dos argumentos: lambda a, b: a + b. Las funciones de Lambda se pueden usar donde se requieran objetos de función. Están sintácticamente restringidos a una sola expresión. Semánticamente, son solo azúcar sintáctico para una definición de función normal. Al igual que las definiciones de funciones anidadas, las funciones lambda pueden hacer referencia a variables del ámbito que las contiene:

In [20]:
def make_incrementor(n):
    return lambda x: x + n

In [21]:
f = make_incrementor(42)

In [22]:
f(0)

42

In [23]:
f(1)

43

El ejemplo anterior usa una expresión lambda para devolver una función. Otro uso es pasar una pequeña función como argumento:

In [24]:
pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]

In [25]:
pairs.sort(key=lambda pair: pair[1])

In [26]:
pairs

[(4, 'four'), (1, 'one'), (3, 'three'), (2, 'two')]

#### 4.7.7. Strings de documentación

Aquí hay algunas convenciones sobre el contenido y el formato de los strings de documentación.

La primera línea siempre debe ser un resumen breve y conciso del propósito del objeto. Por brevedad, no debe indicar explícitamente el nombre o el tipo del objeto, ya que estos están disponibles por otros medios (excepto si el nombre es un verbo que describe la operación de una función). Esta línea debe comenzar con una letra mayúscula y terminar con un punto.

Si hay más líneas en el string de documentación, la segunda línea debe estar en blanco, separando visualmente el resumen del resto de la descripción. Las siguientes líneas deben ser uno o más párrafos que describan las convenciones de llamada del objeto, sus efectos secundarios, etc.

El analizador Python no elimina la sangría de los literales de strings de varias líneas en Python, por lo que las herramientas que procesan la documentación tienen que eliminar la sangría si lo desean. Esto se hace usando la siguiente convención. La primera línea no en blanco después de la primera línea del string determina la cantidad de sangría para todo el string de documentación. (No podemos usar la primera línea ya que generalmente es adyacente a las comillas de apertura del string, por lo que su sangría no es aparente en el string literal). El espacio en blanco "equivalente" a esta sangría se elimina del principio de todas las líneas del string . Las líneas con menos sangría no deberían aparecer, pero si aparecen, se deben eliminar todos los espacios en blanco iniciales. La equivalencia del espacio en blanco debe probarse después de la expansión de las pestañas (a 8 espacios, normalmente).

Aquí hay un ejemplo de un docstring de varias líneas:

In [27]:
def my_function():
    """Do nothing, but document it.
    
    No, really, it doesn't do anything.
    """
    pass

In [28]:
print(my_function.__doc__)

Do nothing, but document it.
    
    No, really, it doesn't do anything.
    


#### 4.7.8. Function annotations

Las anotaciones de funciones son información de metadatos completamente opcional sobre los tipos utilizados por las funciones definidas por el usuario (consulte PEP 3107 y PEP 484 para obtener más información).

Las anotaciones se almacenan en el atributo __anotaciones__ de la función como un diccionario y no tienen efecto en ninguna otra parte de la función. Las anotaciones de parámetros están definidas por dos puntos después del nombre del parámetro, seguido de una expresión que evalúa el valor de la anotación. Las anotaciones de retorno se definen mediante un literal ->, seguido de una expresión, entre la lista de parámetros y los dos puntos que indican el final de la declaración def. El siguiente ejemplo tiene un argumento posicional, un argumento de palabra clave y el valor de retorno anotado:

In [29]:
def f(ham: str, eggs: str = 'eggs') -> str:
    print("Annotations:", f.__annotations__)
    print("Arguments:", ham, eggs)
    return ham + ' and ' + eggs

In [30]:
f('spam')

Annotations: {'ham': <class 'str'>, 'eggs': <class 'str'>, 'return': <class 'str'>}
Arguments: spam eggs


'spam and eggs'

### 4.8. Intermezzo: estilo de codificación

Ahora que está a punto de escribir piezas de Python más largas y complejas, es un buen momento para hablar sobre el estilo de codificación. La mayoría de los idiomas se pueden escribir (o más concisos, formateados) en diferentes estilos; algunos son más legibles que otros. Siempre es una buena idea facilitar que otros lean su código, y adoptar un buen estilo de codificación ayuda enormemente para eso.

Para Python, PEP 8 se ha convertido en la guía de estilo a la que se adhieren la mayoría de los proyectos; promueve un estilo de codificación muy legible y agradable a la vista. Todo desarrollador de Python debería leerlo en algún momento; Aquí están los puntos más importantes extraídos para usted:

   - Use sangría de 4 espacios, y sin pestañas.
   - 4 espacios son un buen compromiso entre una pequeña sangría (permite una mayor profundidad de anidación) y una gran sangría (más fácil de leer). Las pestañas introducen confusión y es mejor dejarlas de lado.
   - Ajuste las líneas para que no superen los 79 caracteres.
   - Esto ayuda a los usuarios con pantallas pequeñas y permite tener varios archivos de código uno al lado del otro en pantallas más grandes.
   - Use líneas en blanco para separar funciones y clases, y bloques de código más grandes dentro de las funciones.
   - Cuando sea posible, coloque los comentarios en una línea propia
   - Usa docstrings.
   - Use espacios alrededor de los operadores y después de las comas, pero no directamente dentro de las construcciones de corchetes: a = f (1, 2) + g (3, 4).
   - Nombre sus clases y funciones consistentemente; la convención es usar UpperCamelCase para clases y minúsculas_con_colecciones para funciones y métodos. Siempre use self como nombre para el primer argumento del método (vea Una primera mirada a las clases para más información sobre clases y métodos).
   - No utilice codificaciones sofisticadas si su código está destinado a ser utilizado en entornos internacionales. El valor predeterminado de Python, UTF-8, o incluso ASCII simple, funciona mejor en cualquier caso.
   - Del mismo modo, no use caracteres que no sean ASCII en los identificadores si existe la más mínima posibilidad de que las personas que hablan un idioma diferente lean o mantengan el código.

## 5. Estructuras de Datos

Este capítulo describe algunas cosas que ya aprendió con más detalle y también agrega algunas cosas nuevas.

### 5.1. Más sobre listas

El tipo de datos de la lista tiene algunos métodos más. Estos son todos los métodos de los objetos de lista:

list.**append**(x)
Agregue un elemento al final de la lista. Equivalente a *a[len(a):] = [x]*.

list.**extend**(iterable)
Extienda la lista agregando todos los elementos del iterable. Equivalente a  *a[len(a):] = iterable*.

list.**insert**(i, x)
Insertar un elemento en una posición determinada. El primer argumento es el índice del elemento antes del cual insertar, por lo que *a.insert(0, x)* se inserta al principio de la lista, y *a.insert(len(a), x)* es equivalente a *a.append(X)*.

list.**remove**(x)
Elimine el primer elemento de la lista cuyo valor es igual a x. Levanta un *ValueError* si no existe tal elemento.

list.**pop**([i])
Elimine el elemento en la posición dada en la lista y devuélvalo. Si no se especifica ningún índice, *a.pop()* elimina y devuelve el último elemento de la lista. (Los corchetes alrededor de la i en la firma del método indican que el parámetro es opcional, no que debe escribir corchetes en esa posición. Verá esta notación con frecuencia en la Referencia de la biblioteca de Python).

list.**clear**()
Eliminar todos los elementos de la lista. Equivalente a del *a[:]*.

list.**index**(x[, start[, end]])
Devuelve el índice basado en cero en la lista del primer elemento cuyo valor es igual a x. Provoca un *ValueError* si no existe dicho elemento.

Los argumentos opcionales start y end se interpretan como en la notación de corte y se usan para limitar la búsqueda a una subsecuencia particular de la lista. El índice devuelto se calcula en relación con el comienzo de la secuencia completa en lugar del argumento de start.

list.**count**(x)
Devuelve el número de veces que x aparece en la lista.

list.**sort**(key = None, reverse = False)
Ordene los elementos de la lista en su lugar (los argumentos se pueden usar para la personalización de la ordenación, consulte *sorted()* para su explicación).

list.**reverse**()
Invierta los elementos de la lista en su lugar.

list.**copy**()
Devuelve una copia superficial de la lista. Equivalente a *a[:]*.

Un ejemplo que usa la mayoría de los métodos de lista:

In [31]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']

In [32]:
fruits.count('apple')

2

In [33]:
fruits.count('tangerine')

0

In [34]:
fruits.index('banana')

3

In [35]:
fruits.index('banana', 4)  # Find next banana starting a position 4

6

In [36]:
fruits.reverse()

In [37]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [38]:
fruits.append('grape')

In [39]:
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [40]:
fruits.sort()

In [41]:
fruits

['apple', 'apple', 'banana', 'banana', 'grape', 'kiwi', 'orange', 'pear']

In [42]:
fruits.pop()

'pear'

Es posible que haya notado que los métodos como *insert*, *remove* u *sort* que solo modifican la lista no tienen ningún valor de retorno impreso; devuelven el valor predeterminado *None*. Este es un principio de diseño para todas las estructuras de datos mutables en Python.

Otra cosa que puede notar es que no todos los datos se pueden ordenar o comparar. Por ejemplo, *[None, 'hello', 10]* no se ordena porque los enteros no se pueden comparar con las cadenas y Ninguno no se puede comparar con otros tipos. Además, hay algunos tipos que no tienen una relación de pedido definida. Por ejemplo, *3 + 4j <5 + 7j* no es una comparación válida.

#### 5.1.1 Usar listas como pilas

Los métodos de lista hacen que sea muy fácil usar una lista como una pila, donde el último elemento agregado es el primer elemento recuperado ("último en entrar, primero en salir"). Para agregar un elemento a la parte superior de la pila, use append(). Para recuperar un elemento desde la parte superior de la pila, use pop() sin un índice explícito. Por ejemplo:

In [43]:
stack = [3, 4, 5]

In [44]:
stack.append(6)

In [45]:
stack.append(7)

In [46]:
stack

[3, 4, 5, 6, 7]

In [47]:
stack.pop()

7

In [48]:
stack

[3, 4, 5, 6]

In [49]:
stack.pop()

6

In [50]:
stack.pop()

5

In [51]:
stack

[3, 4]

#### 5.1.2. Usar listas como Queues

También es posible usar una lista como una queue, donde el primer elemento agregado es el primer elemento recuperado ("primero en entrar, primero en salir"); sin embargo, las listas no son eficientes para este propósito. Si bien los anexos y los estallidos desde el final de la lista son rápidos, hacer inserciones o estallidos desde el principio de una lista es lento (porque todos los demás elementos deben ser desplazados por uno).

Para implementar un queue, use *collections.deque* que fue diseñado para tener adiciones rápidas y pops de ambos extremos. Por ejemplo:

In [52]:
from collections import deque

In [53]:
queue = deque(["Eric", "John", "Michael"])

In [54]:
queue.append("Terry")           # Terry arrives

In [55]:
queue.append("Graham")          # Graham arrives

In [56]:
queue.popleft()                 # The first to arrive now leaves

'Eric'

In [57]:
queue.popleft()                 # The second to arrive now leaves

'John'

In [58]:
queue

deque(['Michael', 'Terry', 'Graham'])

#### 5.1.3. Listas de comprensiones

Las comprensiones de listas proporcionan una forma concisa de crear listas. Las aplicaciones comunes son hacer nuevas listas donde cada elemento es el resultado de algunas operaciones aplicadas a cada miembro de otra secuencia o iterable, o crear una subsecuencia de esos elementos que satisfacen una determinada condición.

Por ejemplo, supongamos que queremos crear una lista de cuadrados, como:

In [59]:
squares = []

In [61]:
for x in range(10):
    squares.append(x**2)

In [62]:
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Tenga en cuenta que esto crea (o sobrescribe) una variable llamada x que todavía existe después de que se completa el ciclo. Podemos calcular la lista de cuadrados sin efectos secundarios usando:

In [63]:
squares = list(map(lambda x: x**2, range(10)))

o equivalente:

In [64]:
squares = [x**2 for x in range(10)]

que es más conciso y legible.

Una comprensión de lista consiste en corchetes que contienen una expresión seguida de una cláusula for, luego cero o más cláusulas for o if. El resultado será una nueva lista resultante de la evaluación de la expresión en el contexto de las cláusulas for y if que le siguen. Por ejemplo, esta listcomp combina los elementos de dos listas si no son iguales:

In [65]:
[(x, y) for x in [1,2,3] for y in [3,1,4] if x != y]

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

y es equivalente a:

In [66]:
combs = []

In [67]:
for x in [1,2,3]:
    for y in [3,1,4]:
        if x != y:
            combs.append((x, y))

In [68]:
combs

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]

Observe cómo el orden de las declaraciones for y if es el mismo en ambos fragmentos.

Si la expresión es una tupla (por ejemplo, (x, y) en el ejemplo anterior), debe estar entre paréntesis.

In [69]:
vec = [-4, -2, 0, 2, 4]

In [70]:
# create a new list with the values doubled
[x*2 for x in vec]

[-8, -4, 0, 4, 8]

In [71]:
# filter the list to exclude negative numbers
[x for x in vec if x >= 0]

[0, 2, 4]

In [72]:
# apply a function to all the elements
[abs(x) for x in vec]

[4, 2, 0, 2, 4]

In [73]:
# call a method on each element
freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']

In [74]:
[weapon.strip() for weapon in freshfruit]

['banana', 'loganberry', 'passion fruit']

In [75]:
# create a list of 2-tuples like (number, square)
[(x, x**2) for x in range(6)]

[(0, 0), (1, 1), (2, 4), (3, 9), (4, 16), (5, 25)]

In [76]:
# the tuple must be parenthesized, otherwise an error is raised
[x, x**2 for x in range(6)]

SyntaxError: invalid syntax (<ipython-input-76-702d12ece8a4>, line 2)

In [77]:
# flatten a list using a listcomp with two 'for'
vec = [[1,2,3], [4,5,6], [7,8,9]]

In [78]:
[num for elem in vec for num in elem]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

Las comprensiones de listas pueden contener expresiones complejas y funciones anidadas:

In [79]:
from math import pi

In [80]:
[str(round(pi, i)) for i in range(1, 6)]

['3.1', '3.14', '3.142', '3.1416', '3.14159']

#### 5.1.4. Listas de Comprensiones anidadas

La expresión inicial en una comprensión de lista puede ser cualquier expresión arbitraria, incluida otra comprensión de lista.

Considere el siguiente ejemplo de una matriz 3x4 implementada como una lista de 3 listas de longitud 4:

In [81]:
matrix = [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
]

La siguiente comprensión de la lista transpondrá filas y columnas:

In [82]:
[[row[i] for row in matrix] for i in range(4)]

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

Como vimos en la sección anterior, el listcomp anidado se evalúa en el contexto de la siguiente, por lo que este ejemplo es equivalente a:

In [83]:
transposed = []

In [84]:
for i in range(4):
    transposed.append([row[i] for row in matrix])

In [85]:
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

que, a su vez, es lo mismo que:

In [86]:
transposed = []

In [88]:
for i in range(4):
    # the following 3 lines implement the nested listcomp
    transposed_row = []
    for row in matrix:
        transposed_row.append(row[i])
    transposed.append(transposed_row)

In [89]:
transposed

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

En el mundo real, debe preferir las funciones integradas a las declaraciones de flujo complejas. La función zip () haría un gran trabajo para este caso de uso:

In [90]:
list(zip(*matrix))

[(1, 5, 9), (2, 6, 10), (3, 7, 11), (4, 8, 12)]

Consulte Desempaquetar listas de argumentos (Cap. 4) para obtener detalles sobre el asterisco en esta línea.

### 5.2. La declaración del

Hay una manera de eliminar un elemento de una lista dado su índice en lugar de su valor: la instrucción *del*. Esto difiere del método pop() que devuelve un valor. La instrucción del también se puede usar para eliminar segmentos de una lista o borrar toda la lista (lo que hicimos anteriormente mediante la asignación de una lista vacía al segmento). Por ejemplo:

In [91]:
a = [-1, 1, 66.25, 333, 333, 1234.5]

In [92]:
del a[0]

In [93]:
a

[1, 66.25, 333, 333, 1234.5]

In [94]:
del a[2:4]

In [95]:
a

[1, 66.25, 1234.5]

In [96]:
del a[:]

In [97]:
a

[]

*del* también se puede usar para eliminar variables completas:

In [98]:
del a

Hacer referencia al nombre *a* aquí en adelante es un error (al menos hasta que se le asigne otro valor). Encontraremos otros usos para *del* más adelante.

### 5.3. Tuplas y Secuencias

Vimos que las listas y las cadenas tienen muchas propiedades comunes, como las operaciones de indexación y corte. Son dos ejemplos de tipos de datos de secuencia (consulte Tipos de secuencia: lista, tupla, rango(https://docs.python.org/3/library/stdtypes.html#typesseq)). Dado que Python es un lenguaje en evolución, se pueden agregar otros tipos de datos de secuencia. También hay otro tipo de datos de secuencia estándar: la tupla.

Una tupla consta de una serie de valores separados por comas, por ejemplo:

In [99]:
t = 12345, 54321, 'hello!'

In [100]:
t[0]

12345

In [101]:
t

(12345, 54321, 'hello!')

In [102]:
# Tuples may be nested:
u = t, (1, 2, 3, 4, 5)

In [103]:
u

((12345, 54321, 'hello!'), (1, 2, 3, 4, 5))

In [104]:
# Tuples are immutable:
t[0] = 88888

TypeError: 'tuple' object does not support item assignment

In [105]:
# but they can contain mutable objects:
v = ([1, 2, 3], [3, 2, 1])

In [106]:
v

([1, 2, 3], [3, 2, 1])

Como puede ver, en la salida las tuplas siempre están encerradas entre paréntesis, de modo que las tuplas anidadas se interpretan correctamente; se pueden ingresar con o sin paréntesis, aunque a menudo los paréntesis son necesarios de todos modos (si la tupla es parte de una expresión más grande). No es posible asignar a los elementos individuales de una tupla, sin embargo, es posible crear tuplas que contienen objetos mutables, como listas.

Aunque las tuplas pueden parecer similares a las listas, a menudo se usan en diferentes situaciones y para diferentes propósitos. Las tuplas son inmutables y, por lo general, contienen una secuencia heterogénea de elementos a los que se accede desempacando (ver más adelante en esta sección) o indexando (o incluso por atributo en el caso de las namedtuples). Las listas son mutables, y sus elementos son generalmente homogéneos y se accede iterando sobre la lista.

Un problema especial es la construcción de tuplas que contienen 0 o 1 elementos: la sintaxis tiene algunas peculiaridades adicionales para acomodarlos. Las tuplas vacías se construyen con un par de paréntesis vacíos; una tupla con un elemento se construye siguiendo un valor con una coma (no es suficiente encerrar un solo valor entre paréntesis). Feo, pero efectivo. Por ejemplo:

In [107]:
empty = ()

In [108]:
singleton = 'hello',    # <-- note trailing comma

In [109]:
len(empty)

0

In [110]:
len(singleton)

1

In [111]:
singleton

('hello',)

La declaración *t = 12345, 54321, 'hello!'* es un ejemplo de empaquetamiento de tuplas: los valores *12345*, *54321* y *'hello!'* están embalados juntos en una tupla. La operación inversa también es posible:

In [112]:
x, y, z = t

Esto se llama, adecuadamente, desempaquetado de secuencia y funciona para cualquier secuencia en el lado derecho. El desempaquetado de secuencia requiere que haya tantas variables en el lado izquierdo del signo igual como elementos en la secuencia. Tenga en cuenta que la asignación múltiple es realmente solo una combinación de empaque de tuplas y desempaque de secuencia.

### 5.4. Conjuntos

Python también incluye un tipo de datos para conjuntos. Un conjunto es una colección desordenada sin elementos duplicados. Los usos básicos incluyen pruebas de membresía y eliminación de entradas duplicadas. Los objetos de conjunto también admiten operaciones matemáticas como unión, intersección, diferencia y diferencia simétrica.

Las llaves o la función set() se pueden usar para crear conjuntos. Nota: para crear un conjunto vacío, debe usar set(), no {}; este último crea un diccionario vacío, una estructura de datos que discutiremos en la siguiente sección.

Aquí hay una breve demostración:

In [113]:
basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}

In [115]:
print(basket)                      # show that duplicates have been removed

{'banana', 'apple', 'orange', 'pear'}


In [116]:
'orange' in basket                 # fast membership testing

True

In [117]:
'crabgrass' in basket

False

In [118]:
# Demonstrate set operations on unique letters from two words
a = set('abracadabra')

In [119]:
b = set('alacazam')

In [120]:
a                                  # unique letters in a

{'a', 'b', 'c', 'd', 'r'}

In [121]:
a - b                              # letters in a but not in b

{'b', 'd', 'r'}

In [122]:
a | b                              # letters in a or b or both

{'a', 'b', 'c', 'd', 'l', 'm', 'r', 'z'}

In [123]:
a & b                              # letters in both a and b

{'a', 'c'}

In [124]:
a ^ b                              # letters in a or b but not both

{'b', 'd', 'l', 'm', 'r', 'z'}

De manera similar a la lista de comprensiones, las comprensiones establecidas también son compatibles:

In [125]:
a = {x for x in 'abracadabra' if x not in 'abc'}

In [126]:
a

{'d', 'r'}

### 5.5. Diccionarios

Otro tipo de datos útil integrado en Python es el diccionario (ver Tipos de mapeo - dict: https://docs.python.org/3/library/stdtypes.html#typesmapping). Los diccionarios a veces se encuentran en otros idiomas como "memorias asociativas" o "matrices asociativas". A diferencia de las secuencias, que están indexadas por un rango de números, los diccionarios están indexados por claves, que pueden ser de cualquier tipo inmutable; Las cadenas y los números siempre pueden ser claves. Las tuplas se pueden usar como claves si contienen solo cadenas, números o tuplas; Si una tupla contiene algún objeto mutable, ya sea directa o indirectamente, no se puede usar como clave. No puede usar listas como claves, ya que las listas se pueden modificar en su lugar mediante asignaciones de índice, asignaciones de sectores o métodos como append() y extend().

Es mejor pensar en un diccionario como un conjunto de claves: pares de valores, con el requisito de que las claves sean únicas (dentro de un diccionario). Un par de llaves crea un diccionario vacío: {}. Al colocar una lista separada por comas de pares clave: valor dentro de las llaves se agrega clave inicial: pares de valores al diccionario; esta es también la forma en que los diccionarios se escriben en la salida.

Las operaciones principales en un diccionario son almacenar un valor con alguna clave y extraer el valor dado la clave. También es posible eliminar una clave: par de valores con *del*. Si almacena utilizando una clave que ya está en uso, se olvida el valor anterior asociado con esa clave. Es un error extraer un valor usando una clave inexistente.

La ejecución de la list(d) en un diccionario devuelve una lista de todas las teclas utilizadas en el diccionario, en orden de inserción (si desea ordenarlas, simplemente use sorted(d) en su lugar). Para verificar si hay una sola clave en el diccionario, use la palabra clave *in*.

Aquí hay un pequeño ejemplo usando un diccionario:

In [127]:
tel = {'jack': 4098, 'sape': 4139}

In [128]:
tel['guido'] = 4127

In [129]:
tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}

In [130]:
tel['jack']

4098

In [131]:
del tel['sape']

In [132]:
tel['irv'] = 4127

In [133]:
tel

{'jack': 4098, 'guido': 4127, 'irv': 4127}

In [134]:
list(tel)

['jack', 'guido', 'irv']

In [135]:
sorted(tel)

['guido', 'irv', 'jack']

In [136]:
'guido' in tel

True

In [137]:
'jack' not in tel

False

El constructor dict() construye diccionarios directamente a partir de secuencias de pares clave-valor:

In [138]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'sape': 4139, 'guido': 4127, 'jack': 4098}

Además, las comprensiones dict se pueden utilizar para crear diccionarios a partir de expresiones de valores y claves arbitrarias:

In [139]:
{x: x**2 for x in (2, 4, 6)}

{2: 4, 4: 16, 6: 36}

Cuando las claves son cadenas simples, a veces es más fácil especificar pares usando argumentos de palabras clave:

In [140]:
dict(sape=4139, guido=4127, jack=4098)

{'sape': 4139, 'guido': 4127, 'jack': 4098}

### 5.6. Técnicas de Bucles

Al recorrer los diccionarios, la clave y el valor correspondiente se pueden recuperar al mismo tiempo utilizando el método items().

In [141]:
knights = {'gallahad': 'the pure', 'robin': 'the brave'}

In [142]:
for k, v in knights.items():
    print(k, v)

gallahad the pure
robin the brave


Al recorrer una secuencia, el índice de posición y el valor correspondiente se pueden recuperar al mismo tiempo utilizando la función enumerate().

In [143]:
for i, v in enumerate(['tic', 'tac', 'toe']):
    print(i, v)

0 tic
1 tac
2 toe


Para recorrer dos o más secuencias al mismo tiempo, las entradas se pueden emparejar con la función zip().

In [144]:
questions = ['name', 'quest', 'favorite color']

In [145]:
answers = ['lancelot', 'the holy grail', 'blue']

In [147]:
for q, a in zip(questions, answers):
    print('What is your {0}?  It is {1}.'.format(q, a))

What is your name?  It is lancelot.
What is your quest?  It is the holy grail.
What is your favorite color?  It is blue.


Para recorrer una secuencia en reversa, primero especifique la secuencia en dirección hacia adelante y luego llame a la función reversed().

In [148]:
for i in reversed(range(1, 10, 2)):
    print(i)

9
7
5
3
1


Para recorrer una secuencia en orden ordenado, use la función sorted() que devuelve una nueva lista ordenada mientras deja la fuente sin alterar.

In [149]:
basket = ['apple', 'orange', 'apple', 'pear', 'orange', 'banana']

In [150]:
for f in sorted(set(basket)):
    print(f)

apple
banana
orange
pear


A veces es tentador cambiar una lista mientras la recorres; sin embargo, a menudo es más simple y seguro crear una nueva lista.

In [151]:
import math

In [152]:
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]

In [153]:
filtered_data = []

In [154]:
for value in raw_data:
    if not math.isnan(value):
        filtered_data.append(value)

In [155]:
filtered_data

[56.2, 51.7, 55.3, 52.5, 47.8]

### 5.7. Mas sobre las Condiciones

Las condiciones utilizadas en las declaraciones *while* y *if* pueden contener cualquier operador, no solo comparaciones.

Los operadores de comparación *in* y *not in* chequean si un valor ocurre (no ocurre) en una secuencia. Los operadores *is* y *is not* comparan si dos objetos son realmente el mismo objeto; esto solo importa para objetos mutables como listas. Todos los operadores de comparación tienen la misma prioridad, que es inferior a la de todos los operadores numéricos.

Las comparaciones se pueden encadenar. Por ejemplo, *a < b == c* prueba si a es menor que b y además *b* es igual a *c*.

Las comparaciones pueden combinarse utilizando los operadores booleanos y y o, y el resultado de una comparación (o de cualquier otra expresión booleana) puede negarse con not. Estos tienen prioridades más bajas que los operadores de comparación; entre ellos, no tiene la prioridad más alta y / o la más baja, de modo que *A and not B or C* es equivalente a *(A and (not B)) or C*. Como siempre, se pueden usar paréntesis para expresar la composición deseada.

Los operadores booleanos *and* y *or* son los llamados operadores de cortocircuito: sus argumentos se evalúan de izquierda a derecha, y la evaluación se detiene tan pronto como se determina el resultado. Por ejemplo, si *A* y *C* son verdaderas pero *B* es falso, *A y B y C* no evalúan la expresión C. Cuando se usa como un valor general y no como un booleano, el valor de retorno de un operador de cortocircuito es el último argumento evaluado

Es posible asignar el resultado de una comparación u otra expresión booleana a una variable. Por ejemplo,

In [156]:
string1, string2, string3 = '', 'Trondheim', 'Hammer Dance'

In [157]:
non_null = string1 or string2 or string3

In [158]:
non_null

'Trondheim'

Tenga en cuenta que en Python, a diferencia de C, la asignación dentro de las expresiones debe hacerse explícitamente con el operador de walrus *:=* (https://docs.python.org/3/faq/design.html#why-can-t-i-use-an-assignment-in-an-expression). Esto evita una clase común de problemas encontrados en los programas en C: escribir *=* en una expresión cuando *==* estaba destinado.

### 5.8 Comparación de secuencias y otros tipos

Los objetos de secuencia generalmente se pueden comparar con otros objetos con el mismo tipo de secuencia. La comparación utiliza el orden *lexicographical*: primero se comparan los dos primeros elementos, y si difieren, esto determina el resultado de la comparación; si son iguales, se comparan los siguientes dos elementos, y así sucesivamente, hasta que se agote cualquiera de las secuencias. Si dos elementos a comparar son secuencias del mismo tipo, la comparación lexicográfica se realiza de forma recursiva. Si todos los elementos de dos secuencias se comparan igual, las secuencias se consideran iguales. Si una secuencia es una subsecuencia inicial de la otra, la secuencia más corta es la más pequeña (menor). El ordenamiento lexicográfico de cadenas utiliza el número de punto de código Unicode para ordenar caracteres individuales. Algunos ejemplos de comparaciones entre secuencias del mismo tipo:

    (1, 2, 3)              < (1, 2, 4)
    [1, 2, 3]              < [1, 2, 4]
    'ABC' < 'C' < 'Pascal' < 'Python'
    (1, 2, 3, 4)           < (1, 2, 4)
    (1, 2)                 < (1, 2, -1)
    (1, 2, 3)             == (1.0, 2.0, 3.0)
    (1, 2, ('aa', 'ab'))   < (1, 2, ('abc', 'a'), 4)

Tenga en cuenta que comparar objetos de diferentes tipos con *<* o *>* es legal siempre que los objetos tengan métodos de comparación apropiados. Por ejemplo, los tipos numéricos mixtos se comparan de acuerdo con su valor numérico, por lo que 0 es igual a 0.0, etc. De lo contrario, en lugar de proporcionar un orden arbitrario, el intérprete generará una excepción *TypeError*.